version: '3'
services:
  cli:
    container_name: cli
    build:
      context: ../../../
      dockerfile: ./cluster/integration-tests/cli/client/Dockerfile
    environment:
      - TEST_ID=${TEST_ID}
      - NSTRUMENTA_API_KEY=${NSTRUMENTA_API_KEY}
      - NSTRUMENTA_WS_URL=ws://cloud:8080
