services:
  frontend:
    image: node:24.12-alpine
    ports:
      - 5008:5008
    volumes:
      - ./frontend:/app
      - ./credentials:/credentials
    environment:
      - PROXY_TARGET=http://server:5999
    working_dir: /app
    command: 'npm run start'
  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - 5999:5999
      - 9229:9229
    volumes:
      - ~/.config/gcloud:/gcp:ro
      - ./server/app/:/app
      - ./credentials/:/credentials
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/gcp/application_default_credentials.json
      - GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT}
      - NSTRUMENTA_CLOUD_RUN_MODE=local
      - NST_AGENT_TYPE=ci
    command: sh -c 'npm run dev'
  agent:
    build:
      context: .
      dockerfile: ./agent/Dockerfile
    ports:
      - 8088:8088
      - 9230:9230
    privileged: true
    volumes:
      - .:/app
    environment:
      - NSTRUMENTA_API_KEY=${NSTRUMENTA_API_KEY}
    command: sh -c 'npm run dev'
