export class SensorEvent {
  id: string;
  timestamp: number;
  values: number[];
}

export const sensorEventLabels = {
  1: {
    name: 'Accelerometer',
    type: 'input',
    traces: ['Acc x', 'Acc y', 'Acc z'],
  },
  2: {
    name: 'Magnetometer',
    type: 'input',
    traces: ['Mag x', 'Mag y', 'Mag z'],
  },
  4: {
    name: 'Gyro',
    type: 'input',
    traces: ['Gyro x', 'Gyro y', 'Gyro z'],
  },
  6: {
    name: 'Pressure',
    type: 'input',
    traces: ['P (mB)'],
  },
  7: {
    name: 'Temperature',
    type: 'input',
    traces: ['Temp(°C)'],
  },
  11: {
    name: 'Rotation Vector',
    type: 'input',
    traces: ['x', 'y', 'z', 'w'],
  },
  20: {
    name: 'Geomagnetic Rotation Vector',
    type: 'input',
    traces: ['x', 'y', 'z', 'w'],
  },
  65200: {
    name: 'Downsample Input',
    type: 'input',
    traces: [
      'microsecond timestamp',
      'q0',
      'q1',
      'q2',
      'q3',
      'acc_x',
      'acc_y',
      'acc_z',
      'lin_acc_x',
      'lin_acc_y',
      'lin_acc_z',
    ],
  },
  65666: {
    name: 'GPS',
    type: 'computed',
    traces: ['lat', 'lon', 'alt', 'hdop', 'pdop', 'speed', 'track', 'vdop'],
  },
  65667: {
    name: 'Vehicle Data',
    type: 'input',
    traces: [
      'Vehicle speed (m/s)',
      'Yaw rate (Degree/Sec)',
      'Steering Wheel (Degree)',
      'Front Left Wheel Speed (m/s)',
      'Front Right Wheel Speed (m/s)',
      'Rear Left Wheel Speed (m/s)',
      'Rear Right Wheel Speed (m/s)',
    ],
  },

  65668: {
    name: 'Applanix',
    type: 'input',
    traces: [
      'latitude',
      'longitude',
      'altitude',
      'roll (degree)',
      'pitch (degree)',
      'heading (degree)',
      'speed (mps)',
    ],
  },
  1002: {
    name: 'Truth Point (Geo coords)',
    type: 'computed',
    traces: ['lat', 'lng', 'altitude'],
  },
  1003: {
    name: 'Angular Error (Fused vs. Applanix)',
    type: 'computed',
    traces: [
      'error mag (degrees)',
      'heading difference mag (degrees)',
      'error gyro (degrees)',
      'heading difference gyro (degrees)',
      'heading(applanix)',
      'pitch(applanix)',
      'roll(applanix)',
      'heading(gyro)',
      'pitch(gyro)',
      'roll(gyro)',
      'applanix delta angle',
    ],
  },
  1006: {
    name: 'Magnetic Field (Filtered vs. Applanix with World Magnetic Model)',
    type: 'computed',
    traces: [
      'mag error magnitude',
      'unfiltered x',
      'unfiltered y',
      'unfiltered z',
      'unfiltered total',
      'filtered x',
      'filtered y',
      'filtered z',
      'filtered total',
      'applanix x',
      'applanix y',
      'applanix z',
      'applanix total',
    ],
  },
  1008: {
    name: 'Fused Mag',
    type: 'computed',
    traces: [
      'latitude',
      'longitude',
      'altitude',
      'roll (degree)',
      'pitch (degree)',
      'heading (degree)',
      'speed (mps)',
    ],
  },
  1009: {
    name: 'Fused Gyro',
    type: 'computed',
    traces: [
      'latitude',
      'longitude',
      'altitude',
      'roll (degree)',
      'pitch (degree)',
      'heading (degree)',
      'speed (mps)',
    ],
  },
  1010: {
    name: 'Position',
    type: 'computed',
    traces: [
      'Position delta magnitude vdr to gps (m)',
      'Position delta magnitude gyro to gps (m)',
      'Position delta magnitude mag+accel to gps (m)',
      'vdr x',
      'vdr y',
      'vdr z',
      'mag x',
      'mag y',
      'mag z',
      'gps x',
      'gps y',
      'gps z',
    ],
  },
  1011: {
    name: 'Fused VDR',
    type: 'computed',
    traces: [
      'latitude',
      'longitude',
      'altitude',
      'roll (degree)',
      'pitch (degree)',
      'heading (degree)',
      'speed (mps)',
    ],
  },
  1012: {
    name: 'Trax2',
    type: 'input',
    traces: [
      'Heading',
      'Pitch',
      'Roll',
      'MagX',
      'MagY',
      'MagZ',
      'AccelX',
      'AccelY',
      'AccelZ',
      'GyroX',
      'GyroY',
      'GyroZ',
      'Heading Status',
      'Temperature',
      'Distortion',
    ],
  },
  2000: {
    name: 'Kalman Quaternion',
    type: 'computed',
    traces: ['x', 'y', 'z', 'w', 'measured x', 'measured y', 'measured z'],
  },
  2001: {
    name: 'Pitch and Roll',
    type: 'computed',
    traces: [
      'Pitch and Roll Error',
      'Acc+Mag heading',
      'Acc pitch',
      'Acc roll',
      'Gyro-prop heading',
      'Gyro-prop pitch',
      'Gyro-prop roll',
    ],
  },
  3000: {
    name: 'Bluecoin',
    type: 'input',
    traces: [],
  },
  3001: {
    name: 'Thingy',
    type: 'input',
    traces: [
      'Bluetooth Acc x',
      'Bluetooth Acc y',
      'Bluetooth Acc z',
      'Bluetooth Gyro x',
      'Bluetooth Gyro y',
      'Bluetooth Gyro z',
      'Bluetooth Mag x',
      'Bluetooth Mag y',
      'Bluetooth Mag z',
    ],
  },
  3002: {
    name: 'Trax',
    type: 'input',
    traces: [
      'Trax timestamp',
      'Trax Acc x',
      'Trax Acc y',
      'Trax Acc z',
      'Trax Gyro x',
      'Trax Gyro y',
      'Trax Gyro z',
      'Trax Mag x',
      'Trax Mag y',
      'Trax Mag z',
    ],
  },
  4001: {
    name: 'LPOM mag raw',
    type: 'input',
    traces: ['LPOM mag_x_raw', 'LPOM mag_y_raw', 'LPOM mag_z_raw', 'LPOM mag_timestamp'],
  },
  4015: {
    name: 'LPOM accel raw',
    type: 'input',
    traces: ['LPOM accel_x_raw', 'LPOM accel_y_raw', 'LPOM accel_z_raw', 'LPOM accel_timestamp'],
  },
  4028: {
    name: 'Fused Location (6DOF)',
    type: 'computed',
    traces: [
      'quaternion x',
      'quaternion y',
      'quaternion z',
      'quaternion w',
      'position x',
      'position y',
      'position z',
    ],
  },
  4062: {
    name: 'LPOM gyro raw',
    type: 'input',
    traces: ['LPOM gyro_x_raw', 'LPOM gyro_y_raw', 'LPOM gyro_z_raw', 'LPOM gyro_timestamp'],
  },
  4077: {
    name: 'q mag/accel',
    type: 'input',
    traces: ['q0_ma', 'q1_ma', 'q2_ma', 'q3_ma'],
  },
  4093: {
    name: 'mag autocal',
    type: 'input',
    traces: ['mag_x_autocal', 'mag_y_autocal', 'mag_z_autocal'],
  },
  4099: {
    name: 'accel autocal',
    type: 'input',
    traces: ['accel_x_autocal', 'accel_y_autocal', 'accel_z_autocal'],
  },
  4108: {
    name: 'gyro autocal',
    type: 'input',
    traces: ['gyro_x_autocal', 'gyro_y_autocal', 'gyro_z_autocal'],
  },
  4111: {
    name: 'LPOM full timestamp',
    type: 'input',
    traces: ['LPOM timestamp lower', 'LPOM timestamp upper'],
  },
  4302: {
    name: 'Fused Location (Geo coords)',
    type: 'computed',
    traces: ['lat', 'lng', 'previous lat', 'previous lng'],
  },
  4200: {
    name: 'Downsample Input',
    type: 'input',
    traces: ['lin_acc_x', 'lin_acc_y', 'lin_acc_z'],
  },
  4201: {
    name: 'DOM',
    type: 'input',
    traces: ['lat', 'lon', 'rssi', 'stepNum', 'length', 'heading'],
  },
  4204: {
    name: '9-Axis Quaternion',
    type: 'input',
    traces: ['q0', 'q1', 'q2', 'q3'],
  },
  4206: {
    name: 'Maxwell',
    type: 'input',
    traces: ['mag x', 'mag y', 'mag z', 'e-field'],
  },
  4207: {
    name: 'Maxwell Fields',
    type: 'input',
    traces: ['B Field STD', 'E Field STD', 'Status'],
  },
  4208: {
    name: 'Maxwell FFT',
    type: 'input',
    traces: ['Frequency FFT', 'B Field FFT', 'E Field FFT', 'Phase FFT'],
  },
  4209: {
    name: 'EOS Frame Diff',
    type: 'input',
    traces: ['difm9', 'difm9grav', 'difg9'],
  },
};
